
name: Deploy GCP

on:
  push:
    branches: [ main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
    - name: Use gcloud CLI
      run: gcloud info
      
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    
    - name: Build
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sharpmicro2:latest .

    - name: Push
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sharpmicro2:latest

    - name: Deploy
      run: |
        gcloud run deploy sharpmicro2  \
        --region northamerica-northeast1  \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/sharpmicro2  \
        --platform managed \
        --allow-unauthenticated \
        --project ${{ secrets.GCP_PROJECT_ID }} \
        --memory=8Gi \
        --cpu=2 